num1 = 10
num2 = 20
num3 = num1 + num2
puts "num1 + num2 = #{num1 + num2}"
puts "num1 - num2 = #{num1 - num2}"
puts "num1 * num2 = #{num1 * num2}"
puts "num1 / num2 = #{num1 / num2}"
puts "num1 % num2 = #{num1 % num2}"
puts "num1 ** num2 = #{num1 ** num2}"
puts "num1 < num2 = #{num1 < num2}"
puts "num1 > num2 = #{num1 > num2}"
puts "num1 <= num2 = #{num1 <= num2}"
puts "num1 >= num2 = #{num1 >= num2}"
puts "num1 == num2 = #{num1 == num2}"
puts "num1 != num2 = #{num1 != num2}"
puts "num1 <=> num2 = #{num1 <=> num2}"
puts "num1 == num2 = #{num1 == num2}"
puts "num1 != num2 = #{num1 != num2}"
puts "num1.abs = #{num1.abs}"
puts "num1.ceil = #{num1.ceil}"
puts "num1.floor = #{num1.floor}"
puts "num1.round = #{num1.round}"
puts "num2.abs = #{num2.abs}"
puts "num2.ceil = #{num2.ceil}"
puts "num2.floor = #{num2.floor}"
puts "num2round = #{num2.round}"
puts "num1.to_s = #{num1.to_s}"
puts "num1.to_i = #{num1.to_i}"
puts "num1.to_f = #{num1.to_f}"
puts "num1.to_r = #{num1.to_r}"
puts "num1.to_c = #{num1.to_c}"
